<?php
	
	/*
		Generated ACF Pages
	*/


	if( function_exists('acf_add_options_page') ) {
		
		acf_add_options_page(array(
			'page_title' => 'Theme Settings',
			'menu_title' => 'Theme Settings',
			'menu_slug' => 'theme-settings',
			'capability' => 'edit_posts',
			'parent_slug' => '',
			'position' => false,
			'icon_url' => false,
			'redirect' => false
		));
		
		acf_add_options_sub_page(array(
			'page_title' => 'Business Information',
			'menu_title' => 'Business Information',
			'menu_slug' => 'theme-settings-business-information',
			'capability' => 'edit_posts',
			'parent_slug' => 'theme-settings',
			'position' => false,
			'icon_url' => false
		));
	
	}
	
	/* Generated ACF Fields */
	
	if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_58e46cdc80981',
	'title' => 'Business Information',
	'fields' => array(
		array(
			'key' => 'field_58ec1af879c5f',
			'label' => 'Business Information',
			'name' => 'business_information',
			'type' => 'repeater',
			'instructions' => 'Enter business information below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_58ec1d346dcf4',
					'label' => 'Office Title',
					'name' => 'office_title',
					'type' => 'text',
					'instructions' => 'If there is only one office, recommended title is "Office Information". For members with multiple locations, enter a title that defines the different offices.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Office Information',
					'placeholder' => 'Office Information',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec1b3e79c60',
					'label' => 'Monday',
					'name' => 'monday',
					'type' => 'text',
					'instructions' => 'Use the following hours format for best results: "8:00am - 5:00pm" or "Closed".',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '8:00am - 5:00pm',
					'placeholder' => '8:00am - 5:00pm',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec1b8e79c61',
					'label' => 'Tuesday',
					'name' => 'tuesday',
					'type' => 'text',
					'instructions' => 'Use the following hours format for best results: "8:00am - 5:00pm" or "Closed".',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '8:00am - 5:00pm',
					'placeholder' => '8:00am - 5:00pm',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec1b9e79c62',
					'label' => 'Wednesday',
					'name' => 'wednesday',
					'type' => 'text',
					'instructions' => 'Use the following hours format for best results: "8:00am - 5:00pm" or "Closed".',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '8:00am - 5:00pm',
					'placeholder' => '8:00am - 5:00pm',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec1bb079c63',
					'label' => 'Thursday',
					'name' => 'thursday',
					'type' => 'text',
					'instructions' => 'Use the following hours format for best results: "8:00am - 5:00pm" or "Closed".',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '8:00am - 5:00pm',
					'placeholder' => '8:00am - 5:00pm',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec1bbc79c64',
					'label' => 'Friday',
					'name' => 'friday',
					'type' => 'text',
					'instructions' => 'Use the following hours format for best results: "8:00am - 5:00pm" or "Closed".',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '8:00am - 5:00pm',
					'placeholder' => '8:00am - 5:00pm',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec1bc779c65',
					'label' => 'Saturday',
					'name' => 'saturday',
					'type' => 'text',
					'instructions' => 'Use the following hours format for best results: "8:00am - 5:00pm" or "Closed".',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '8:00am - 5:00pm',
					'placeholder' => '8:00am - 5:00pm',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec1bd279c66',
					'label' => 'Sunday',
					'name' => 'sunday',
					'type' => 'text',
					'instructions' => 'Use the following hours format for best results: "8:00am - 5:00pm" or "Closed".',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '8:00am - 5:00pm',
					'placeholder' => '8:00am - 5:00pm',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec1bdd79c67',
					'label' => 'Office Hours Note',
					'name' => 'hours_note',
					'type' => 'text',
					'instructions' => 'For additional hours information such as lunch hours, enter the note here.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec285f81733',
					'label' => 'Office Phone',
					'name' => 'office_phone',
					'type' => 'text',
					'instructions' => 'Enter the office location phone number.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec291681735',
					'label' => 'Office Fax',
					'name' => 'office_fax',
					'type' => 'text',
					'instructions' => 'Enter the office location phone number.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec28e181734',
					'label' => 'Office Email',
					'name' => 'office_email',
					'type' => 'text',
					'instructions' => 'Enter the office locations email address.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec292081736',
					'label' => 'Office Address',
					'name' => 'office_address',
					'type' => 'text',
					'instructions' => 'Enter the office locations street address.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec292d81737',
					'label' => 'Office Address Cont.',
					'name' => 'office_address_cont',
					'type' => 'text',
					'instructions' => 'Enter the office locations continued street address (Suite #..ect).',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec296081738',
					'label' => 'Office City',
					'name' => 'office_city',
					'type' => 'text',
					'instructions' => 'Enter the office locations city.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec297981739',
					'label' => 'Office State',
					'name' => 'office_state',
					'type' => 'text',
					'instructions' => 'Enter the office locations state.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ec29858173a',
					'label' => 'Office Zipcode',
					'name' => 'office_zipcode',
					'type' => 'text',
					'instructions' => 'Enter the office locations zip code.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58ee4c83ff1b3',
					'label' => 'Social Accounts',
					'name' => 'social_accounts',
					'type' => 'repeater',
					'instructions' => 'Please enter social account links you would like to display.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_58ee4cb5ff1b4',
							'label' => 'Social URL',
							'name' => 'social_url',
							'type' => 'text',
							'instructions' => 'Insert the social link you would like to feature.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-settings-business-information',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_58e93c44b980c',
	'title' => 'Website Settings',
	'fields' => array(
		array(
			'key' => 'field_5a9b0b9d9eb98',
			'label' => 'Website Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58e93c4a39ac0',
			'label' => 'Home Page Selection',
			'name' => 'home_selection',
			'type' => 'radio',
			'instructions' => 'Select the type of home page you want to feature.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full' => 'Static (Full)',
				'fixed' => 'Static (Fixed)',
				'slide' => 'Slideshow (Full)',
				'slidefix' => 'Slideshow (Fixed)',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'full',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5a95fc25d965a',
			'label' => 'Slideshow',
			'name' => 'slideshow',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58e93c4a39ac0',
						'operator' => '==',
						'value' => 'slide',
					),
				),
				array(
					array(
						'field' => 'field_58e93c4a39ac0',
						'operator' => '==',
						'value' => 'slidefix',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Slide',
			'sub_fields' => array(
				array(
					'key' => 'field_5a95ff4b107e6',
					'label' => 'Slide',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '<h3>Slide image handled programmatically, caption can be found below.</h3>',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_5a95fc99d965c',
					'label' => 'Caption',
					'name' => 'caption',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'text',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_58ec072ce8889',
			'label' => 'Home Logo',
			'name' => 'home_logo',
			'type' => 'radio',
			'instructions' => 'Select to display the home logo section, site description, and home page navigation.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'image' => 'Image',
				'text' => 'Text',
				'none' => 'None',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ad3b6438ea29',
			'label' => 'Home Logo Text',
			'name' => 'home_logo_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58ec072ce8889',
						'operator' => '==',
						'value' => 'text',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_58ec00ba95910',
			'label' => 'Home Logo / Navigation Location',
			'name' => 'home_logo_location',
			'type' => 'radio',
			'instructions' => 'Select how you want the home logo, site description, and home page menu aligned. Left, Center, Right are the options.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58ec072ce8889',
						'operator' => '==',
						'value' => 'image',
					),
				),
				array(
					array(
						'field' => 'field_58ec072ce8889',
						'operator' => '==',
						'value' => 'text',
					),
				),
				array(
					array(
						'field' => 'field_58ec072ce8889',
						'operator' => '==',
						'value' => 'none',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Left',
				'center' => 'Center',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'center',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ac521699eb23',
			'label' => 'Website Navigation',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ac521cb9eb24',
			'label' => 'Navigation Location',
			'name' => 'navigation_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top (Horizontal)',
				'bottom' => 'Bottom (Horizontal)',
				'left' => 'Left (Vertical)',
				'right' => 'Right (Vertical)',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'top',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ac522429eb25',
			'label' => 'Header Social Location',
			'name' => 'header_social_location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'both' => 'Both',
				'topbar' => 'Top Bar',
				'mainbar' => 'Main Bar',
				'none' => 'None',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ac52e2d2b604',
			'label' => 'Display Top Bar',
			'name' => 'display_top_bar',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'display' => 'Display',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ace9ae096328',
			'label' => 'Generic Page Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ace9b1196329',
			'label' => 'Call Out Boxes',
			'name' => 'call_out_boxes',
			'type' => 'repeater',
			'instructions' => 'Add a call out box item here. You can have up to 5 items here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 5,
			'layout' => 'row',
			'button_label' => 'Add Call Out',
			'sub_fields' => array(
				array(
					'key' => 'field_5ace9b699632a',
					'label' => 'Call Out Type',
					'name' => 'call_out_type',
					'type' => 'radio',
					'instructions' => 'Select an option below.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'icon' => 'Icon',
						'image' => 'Image',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5ace9ba19632b',
					'label' => 'Icon',
					'name' => 'icon',
					'type' => 'text',
					'instructions' => 'Icon Choices: expand, search, eye, camera, location, quotes-left, quotes-right, numbered-list, square-list, circle-list, menu, eye3, share, googleplus, facebook, instagram, twitter, rss, youtube, vimeo, tumblr, linkedin, pinterest, yelp, spoon-knife, github, codepen, mouse, search-light, sunglasses, calendar, keyboard_arrow_up, keyboard_arrow_right, keyboard_arrow_left, keyboard_arrow_down, user, check, close, blog, arrow-left, arrow-right, plus, asterisk, eye2, arrow-up, arrow-down, cart, settings, phone, users, mail, blurb, download, upload, doctor, stethoscope, desktop, laptop, tablet, mobile, file, pdf, visa, mastercard, discover, americanexpress, creditcard',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ace9b699632a',
								'operator' => '==',
								'value' => 'icon',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5ace9c249632c',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => 'Select an image file.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5ace9b699632a',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5ace9c5f9632d',
					'label' => 'Shape',
					'name' => 'shape',
					'type' => 'radio',
					'instructions' => 'Select a shape for your icon/image.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'circle' => 'Circle',
						'square' => 'Square',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5ace9c889632e',
					'label' => 'Content',
					'name' => 'content',
					'type' => 'wysiwyg',
					'instructions' => 'Insert content here, accepts HTML.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'text',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_5ace9cff96330',
			'label' => 'Use Parallax Feature',
			'name' => 'use_parallax_feature',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'display' => 'Display',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ace9ccb9632f',
			'label' => 'Parallax Content',
			'name' => 'parallax',
			'type' => 'wysiwyg',
			'instructions' => 'Insert parallax content below.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ace9cff96330',
						'operator' => '==',
						'value' => 'display',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'text',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5a9b0bc39eb99',
			'label' => 'Website Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58f6e76875b84',
			'label' => 'Footer Type',
			'name' => 'footer_type',
			'type' => 'radio',
			'instructions' => 'Select a footer type to feature.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'standard' => 'Standard',
				'simple' => 'Simple',
				'none' => 'None',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ad3bb9e899ab',
			'label' => 'Mobile Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ad3bbb0899ac',
			'label' => 'Mobile Header Bar',
			'name' => 'mobile_header_bar',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'simple' => 'Simple',
				'advanced' => 'Advanced',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5a9b0bd59eb9a',
			'label' => 'Miscellaneous',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58ec10c2e7e34',
			'label' => 'Display Search',
			'name' => 'display_search',
			'type' => 'checkbox',
			'instructions' => 'Select to display the search button in the lower right hand portion of the screen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'display' => 'Display',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
				0 => 'display',
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ac52b7175517',
			'label' => 'Search Location',
			'name' => 'search_location',
			'type' => 'radio',
			'instructions' => 'Select the location of the search button.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58ec10c2e7e34',
						'operator' => '==',
						'value' => 'display',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'topright' => 'Top Right',
				'topleft' => 'Top Left',
				'bottomright' => 'Bottom Right',
				'bottomleft' => 'Bottom Left',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58f862905795c',
			'label' => 'Member Login Bar',
			'name' => 'member_login_bar',
			'type' => 'checkbox',
			'instructions' => 'Select to display member login bar at the top of the page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'display' => 'Display',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_58e7ecf9d91aa',
	'title' => 'Page Settings',
	'fields' => array(
		array(
			'key' => 'field_5a9b0b2c6347d',
			'label' => 'Page Settings',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58f7a66959e17',
			'label' => 'Page Sub heading',
			'name' => 'page_sub_heading',
			'type' => 'text',
			'instructions' => 'Insert a sub heading for the page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ad13fc4ce987',
			'label' => 'Secondary Navigation',
			'name' => 'secondary_navigation',
			'type' => 'checkbox',
			'instructions' => 'Display secondary navigation? (requires menu applied to secondary navigation)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'display' => 'Display',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58e7fcde1e7aa',
			'label' => 'Default Editor',
			'name' => 'default_editor',
			'type' => 'checkbox',
			'instructions' => 'Select to display the default editor on the page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Display' => 'Display',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
				0 => 'Display',
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58e9353a38a37',
			'label' => 'Sidebar Selection',
			'name' => 'sidebar_selection',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58e7fcde1e7aa',
						'operator' => '==',
						'value' => 'Display',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Left',
				'none' => 'None',
				'right' => 'Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'right',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5acfe37a16b41',
			'label' => 'Call Out Boxes',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5acfe39316b42',
			'label' => 'Display Call Out Boxes',
			'name' => 'display_call_out_boxes',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'display' => 'Display',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5ad032b981a58',
			'label' => 'Shuffle Call Out Boxes',
			'name' => 'shuffle_call_out_boxes',
			'type' => 'checkbox',
			'instructions' => 'Would you like to shuffle call out box items?',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5acfe39316b42',
						'operator' => '==',
						'value' => 'display',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'yes' => 'Yes',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5a9b0b426347e',
			'label' => 'Parallax Feature',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58e93330e3984',
			'label' => 'Use Parallax Feature',
			'name' => 'parallax_feature',
			'type' => 'radio',
			'instructions' => 'Select a parallax feature below.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Default',
				'custom' => 'Custom',
				'none' => 'None',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'none',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58e972f9ded70',
			'label' => 'Parallax Content',
			'name' => 'parallax_content',
			'type' => 'wysiwyg',
			'instructions' => 'If parallax feature is active, insert content here.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58e93330e3984',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'text',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5a9b0b586347f',
			'label' => 'Appointment Feature',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58e7ed16bb383',
			'label' => 'Appointment Feature',
			'name' => 'appointment_feature',
			'type' => 'checkbox',
			'instructions' => 'Select to display the appointment feature on the page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Display' => 'Display',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
				0 => 'Display',
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_58f81176935bf',
	'title' => 'Page Features',
	'fields' => array(
		array(
			'key' => 'field_5a9b0aca67c8c',
			'label' => 'Gallery',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5915295872546',
			'label' => 'Gallery',
			'name' => 'gallery',
			'type' => 'checkbox',
			'instructions' => 'Use gallery feature?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'use' => 'Use',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5915299b72547',
			'label' => 'Gallery Content',
			'name' => 'gallery_content',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5915295872546',
						'operator' => '==',
						'value' => 'use',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Gallery Item',
			'sub_fields' => array(
				array(
					'key' => 'field_591529bc72549',
					'label' => 'Gallery Image',
					'name' => 'gallery_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
		array(
			'key' => 'field_5a9b0ada67c8d',
			'label' => 'Accordion',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58f8146d961af',
			'label' => 'Accordion',
			'name' => 'accordion',
			'type' => 'checkbox',
			'instructions' => 'Use accordion feature?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'use' => 'Use',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58f8117bcce06',
			'label' => 'Accordion Content',
			'name' => 'accordion_content',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f8146d961af',
						'operator' => '==',
						'value' => 'use',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Section',
			'sub_fields' => array(
				array(
					'key' => 'field_58f814c0961b0',
					'label' => 'Section Heading',
					'name' => 'section_heading',
					'type' => 'text',
					'instructions' => 'Inset a section heading.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58f814ed961b1',
					'label' => 'Section Content',
					'name' => 'section_content',
					'type' => 'wysiwyg',
					'instructions' => 'Insert the content for the accoridan section.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_5a9b0af067c8e',
			'label' => 'Tabs',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58f811b54f473',
			'label' => 'Tabs',
			'name' => 'tabs',
			'type' => 'checkbox',
			'instructions' => 'Use tabs feature?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'use' => 'Use',
			),
			'allow_custom' => 0,
			'save_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58f815471d7bb',
			'label' => 'Tabs Content',
			'name' => 'tabs_content',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_58f811b54f473',
						'operator' => '==',
						'value' => 'use',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Section',
			'sub_fields' => array(
				array(
					'key' => 'field_58f815b41d7be',
					'label' => 'Section Number',
					'name' => 'section_number',
					'type' => 'number',
					'instructions' => 'Number the sections 1-6 in order.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => 5,
					'step' => 1,
				),
				array(
					'key' => 'field_58f815671d7bc',
					'label' => 'Section Heading',
					'name' => 'section_heading',
					'type' => 'text',
					'instructions' => 'Insert a section heading.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_58f815a21d7bd',
					'label' => 'Section Content',
					'name' => 'section_content',
					'type' => 'wysiwyg',
					'instructions' => 'Insert section content.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
	
?>