<?php
	
	/*
		Generated ACF Pages
	*/


	if( function_exists('acf_add_options_page') ) {
		
		acf_add_options_page(array(
			'page_title' => 'Theme Settings',
			'menu_title' => 'Theme Settings',
			'menu_slug' => 'theme-settings',
			'capability' => 'edit_posts',
			'parent_slug' => '',
			'position' => false,
			'icon_url' => false,
			'redirect' => false
		));
		
		acf_add_options_page(array(
			'page_title' => 'Website Content',
			'menu_title' => 'Website Content',
			'menu_slug' => 'website-content',
			'capability' => 'edit_posts',
			'parent_slug' => '',
			'position' => false,
			'icon_url' => false,
			'redirect' => false
		));
	
	}
	
	/* Theme Fields */
	
	if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5ba509fcb7c0b',
		'title' => 'Website Content',
		'fields' => array(
			array(
				'key' => 'field_5ba50a1e28fca',
				'label' => 'Social Media',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ba50a3828fcb',
				'label' => 'Social Media',
				'name' => 'social_media',
				'type' => 'repeater',
				'instructions' => 'Insert your social media links below. You can search for Icon choices at <a href="https://fontawesome.com/" target="_blank">fontawesome.com</a>.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Link',
				'sub_fields' => array(
					array(
						'key' => 'field_5ba50c503e102',
						'label' => 'Social Media Icon',
						'name' => 'social_media_icon',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba50a5828fcc',
						'label' => 'Social Media Link',
						'name' => 'social_media_link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5ba50dce7cfa4',
				'label' => 'Contact Information',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ba50de87cfa5',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'type' => 'repeater',
				'instructions' => 'Insert phone numbers below. You can search for Icon choices at <a href="https://fontawesome.com/" target="_blank">fontawesome.com</a>.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Phone Number',
				'sub_fields' => array(
					array(
						'key' => 'field_5ba50e387cfa6',
						'label' => 'Link Number',
						'name' => 'link_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba50e4b7cfa7',
						'label' => 'Display Number',
						'name' => 'display_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba544ce8d1dd',
						'label' => 'Display Icon (Optional)',
						'name' => 'display_icon',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5ba50e637cfa8',
				'label' => 'Fax Number',
				'name' => 'fax_number',
				'type' => 'repeater',
				'instructions' => 'Insert fax numbers below. You can search for Icon choices at <a href="https://fontawesome.com/" target="_blank">fontawesome.com</a>.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Fax Number',
				'sub_fields' => array(
					array(
						'key' => 'field_5ba50e637cfa9',
						'label' => 'Link Number',
						'name' => 'link_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba50e637cfaa',
						'label' => 'Display Number',
						'name' => 'display_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba544e78d1de',
						'label' => 'Display Icon (Optional)',
						'name' => 'display_icon',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5ba50e8e7cfab',
				'label' => 'Email Address',
				'name' => 'email_address',
				'type' => 'repeater',
				'instructions' => 'Insert email addresses below. You can search for Icon choices at <a href="https://fontawesome.com/" target="_blank">fontawesome.com</a>.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Email',
				'sub_fields' => array(
					array(
						'key' => 'field_5ba50e8e7cfac',
						'label' => 'Link Email',
						'name' => 'link_email',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba50e8e7cfad',
						'label' => 'Display Email',
						'name' => 'display_email',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba544fc8d1df',
						'label' => 'Display Icon (Optional)',
						'name' => 'display_icon',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5ba514a6972c0',
				'label' => 'Business Address',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ba514c2972c1',
				'label' => 'Business Address',
				'name' => 'business_address',
				'type' => 'repeater',
				'instructions' => 'Insert business addresses below.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Address',
				'sub_fields' => array(
					array(
						'key' => 'field_5ba514e1972c2',
						'label' => 'Street Address',
						'name' => 'street_address',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba514ec972c3',
						'label' => 'Street Address (Cont.)',
						'name' => 'street_address_cont',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba514f9972c4',
						'label' => 'City',
						'name' => 'city',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba51506972c5',
						'label' => 'State',
						'name' => 'state',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ba5150d972c6',
						'label' => 'Zip',
						'name' => 'zip',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5ba50f1701afb',
				'label' => 'Business Hours',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ba994702937a',
				'label' => 'Hours Title',
				'name' => 'hours_title',
				'type' => 'text',
				'instructions' => 'Insert a sidebar title here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ba50f2901afc',
				'label' => 'Monday Hours',
				'name' => 'monday_hours',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ba50f4101afd',
				'label' => 'Tuesday Hours',
				'name' => 'tuesday_hours',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ba50f4701afe',
				'label' => 'Wednesday Hours',
				'name' => 'wednesday_hours',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ba50f4e01aff',
				'label' => 'Thursday Hours',
				'name' => 'thursday_hours',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ba50f5301b00',
				'label' => 'Friday Hours',
				'name' => 'friday_hours',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ba50f5901b01',
				'label' => 'Saturday Hours',
				'name' => 'saturday_hours',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ba50f5e01b02',
				'label' => 'Sunday Hours',
				'name' => 'sunday_hours',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ba50f6301b03',
				'label' => 'Hours Note',
				'name' => 'hours_note',
				'type' => 'textarea',
				'instructions' => 'Special hours note can be inserted here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'website-content',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_58e93c44b980c',
		'title' => 'Website Settings',
		'fields' => array(
			array(
				'key' => 'field_5a9b0b9d9eb98',
				'label' => 'Website Header',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58e93c4a39ac0',
				'label' => 'Home Page Header Selection',
				'name' => 'home_selection',
				'type' => 'radio',
				'instructions' => 'Select the type of home page header you want to feature.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'full' => 'Static (Full)',
					'fixedtall' => 'Static (Tall)',
					'fixedshort' => 'Static (Short)',
					'slide' => 'Slideshow (Full)',
					'slidetall' => 'Slideshow (Tall)',
					'slideshort' => 'Slideshow (Short)',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'full',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5a95fc25d965a',
				'label' => 'Home Page Slideshow',
				'name' => 'slideshow',
				'type' => 'repeater',
				'instructions' => 'Add slider image placeholders and captions below.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58e93c4a39ac0',
							'operator' => '==',
							'value' => 'slide',
						),
					),
					array(
						array(
							'field' => 'field_58e93c4a39ac0',
							'operator' => '==',
							'value' => 'slidetall',
						),
					),
					array(
						array(
							'field' => 'field_58e93c4a39ac0',
							'operator' => '==',
							'value' => 'slideshort',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Slide',
				'sub_fields' => array(
					array(
						'key' => 'field_5a95ff4b107e6',
						'label' => 'Slide',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => '<h3>Slide image handled programmatically, caption can be found below.</h3>',
						'new_lines' => 'wpautop',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_5a95fc99d965c',
						'label' => 'Caption',
						'name' => 'caption',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'text',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5b2ae2e77d242',
				'label' => 'Header Image / Slideshow Overlay',
				'name' => 'imageslideshow_overlay',
				'type' => 'checkbox',
				'instructions' => 'Would you like to enable an overlay on top of the header image or slideshow?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'enable' => 'Enable',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_58ec072ce8889',
				'label' => 'Home Page Logo / Text',
				'name' => 'home_logo',
				'type' => 'radio',
				'instructions' => 'Select to display the home logo section and/or site description.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'image' => 'Image',
					'imagetext' => 'Image & Text',
					'text' => 'Text',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ad3b6438ea29',
				'label' => 'Home Page Logo Text',
				'name' => 'home_logo_text',
				'type' => 'textarea',
				'instructions' => 'Insert html code below for website header sub heading.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58ec072ce8889',
							'operator' => '==',
							'value' => 'text',
						),
					),
					array(
						array(
							'field' => 'field_58ec072ce8889',
							'operator' => '==',
							'value' => 'imagetext',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_58ec00ba95910',
				'label' => 'Home Page Logo / Text / Navigation Location',
				'name' => 'home_logo_location',
				'type' => 'radio',
				'instructions' => 'Select how you want the home logo, site description, and home page menu aligned. Left, Center, Right are the options.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58ec072ce8889',
							'operator' => '==',
							'value' => 'image',
						),
					),
					array(
						array(
							'field' => 'field_58ec072ce8889',
							'operator' => '==',
							'value' => 'text',
						),
					),
					array(
						array(
							'field' => 'field_58ec072ce8889',
							'operator' => '==',
							'value' => 'imagetext',
						),
					),
					array(
						array(
							'field' => 'field_58ec072ce8889',
							'operator' => '==',
							'value' => 'none',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left' => 'Left',
					'center' => 'Center',
					'right' => 'Right',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'center',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba9c036d1ff5',
				'label' => 'Back Page Heading Location',
				'name' => 'back_page_heading_location',
				'type' => 'radio',
				'instructions' => 'Select the location of the heading and sub heading on back pages.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left' => 'Left',
					'center' => 'Center',
					'right' => 'Right',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba51a949718d',
				'label' => 'Top Bar',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ba919989e08d',
				'label' => 'Utilize Top Bar',
				'name' => 'utilize_top_bar',
				'type' => 'radio',
				'instructions' => 'Select to display the top bar on the website which includes contact information and/or social media links.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba51ea4406a1',
				'label' => 'Top Bar Style',
				'name' => 'top_bar_style',
				'type' => 'radio',
				'instructions' => 'Should the top bar span the full width of the page or be contained?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba919989e08d',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'fullwidth' => 'Full Width',
					'containerwidth' => 'Container Width',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'fullwidth',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba51ab39718e',
				'label' => 'Top Bar Features',
				'name' => 'top_bar_features',
				'type' => 'radio',
				'instructions' => 'Should the top bar feature contact information and/or social media links?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba919989e08d',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'both' => 'Both',
					'phoneemail' => 'Phone & Email',
					'socialmedia' => 'Social Media',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ac521699eb23',
				'label' => 'Website Navigation',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ba91bf0eed76',
				'label' => 'Utilize Navigation Bar',
				'name' => 'utilize_nav_bar',
				'type' => 'radio',
				'instructions' => 'Do you want your site to have a primary navigation bar?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba4628babc47',
				'label' => 'Navigation Bar Style',
				'name' => 'navigation_bar_style',
				'type' => 'radio',
				'instructions' => 'Should the navigation bar span the full width of the browser window, or be contained?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba91bf0eed76',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'fullwidth' => 'Full Width',
					'containerwidth' => 'Container Width',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'fullwidth',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ac521cb9eb24',
				'label' => 'Navigation Location',
				'name' => 'navigation_location',
				'type' => 'radio',
				'instructions' => 'Where should the navigation bar be displayed in the header?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba91bf0eed76',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'top' => 'Top',
					'bottom' => 'Bottom',
					'full' => 'Full Width',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'top',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba55056480d1',
				'label' => 'Navigation Bar Logo',
				'name' => 'navigation_bar_logo',
				'type' => 'radio',
				'instructions' => 'Should the navigation bar include a logo?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba91bf0eed76',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'display',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5b7b2868845ab',
				'label' => 'Navigation Logo Location',
				'name' => 'navigation_logo_location',
				'type' => 'radio',
				'instructions' => 'Where should the logo be located?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba91bf0eed76',
							'operator' => '==',
							'value' => 'display',
						),
						array(
							'field' => 'field_5ba55056480d1',
							'operator' => '==',
							'value' => 'display',
						),
						array(
							'field' => 'field_5ac521cb9eb24',
							'operator' => '==',
							'value' => 'full',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left' => 'Left',
					'center' => 'Center',
					'right' => 'Right',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ac522429eb25',
				'label' => 'Navigation Bar Social Media',
				'name' => 'navigation_bar_social_media',
				'type' => 'radio',
				'instructions' => 'Should the navigation bar include social media links?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba91bf0eed76',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'none',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba94330bbfac',
				'label' => 'Navigation Bar Arrows',
				'name' => 'navigation_bar_arrows',
				'type' => 'radio',
				'instructions' => 'Should the primary level navigation include dark or light arrows for sub menu\'s?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba91bf0eed76',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'dark' => 'Dark Arrows',
					'light' => 'Light Arrows',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba9453753341',
				'label' => 'Scrolling Navigation Bar Arrows',
				'name' => 'scrolling_navigation_bar_arrows',
				'type' => 'radio',
				'instructions' => 'While scrolling down the page, should the primary navigation include dark or light arrows?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba91bf0eed76',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'dark' => 'Dark Arrows',
					'light' => 'Light Arrows',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ace9ae096328',
				'label' => 'Page Features',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ace9b1196329',
				'label' => 'Call Out Boxes',
				'name' => 'call_out_boxes',
				'type' => 'repeater',
				'instructions' => 'Add a call out box item here. You can have up to 5 items here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 5,
				'layout' => 'row',
				'button_label' => 'Add Call Out',
				'sub_fields' => array(
					array(
						'key' => 'field_5ace9b699632a',
						'label' => 'Call Out Type',
						'name' => 'call_out_type',
						'type' => 'radio',
						'instructions' => 'Select an option below.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'icon' => 'Icon',
							'image' => 'Image',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5ace9ba19632b',
						'label' => 'Icon',
						'name' => 'icon',
						'type' => 'text',
						'instructions' => 'You can search for Icon choices at <a href="https://fontawesome.com/" target="_blank">fontawesome.com</a>.',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ace9b699632a',
									'operator' => '==',
									'value' => 'icon',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ace9c249632c',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Select an image file.',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_5ace9b699632a',
									'operator' => '==',
									'value' => 'image',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5ace9c5f9632d',
						'label' => 'Shape',
						'name' => 'shape',
						'type' => 'radio',
						'instructions' => 'Select a shape for your icon/image.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'circle' => 'Circle',
							'square' => 'Square',
						),
						'allow_null' => 0,
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5ace9c889632e',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'wysiwyg',
						'instructions' => 'Insert content here, accepts HTML.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'text',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5bae6bcbaffb9',
				'label' => 'Attention Header Style',
				'name' => 'attention_header_style',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'fullwidth' => 'Full Width',
					'containerwidth' => 'Container Width',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'fullwidth',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5baa5a53341c1',
				'label' => 'Attention Box Style',
				'name' => 'attention_box_style',
				'type' => 'radio',
				'instructions' => 'If your page includes an attention widget, should it be displayed in a horizontal or vertical format?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'horizontal' => 'Horizontal',
					'vertical' => 'Vertical',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'vertical',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ace9cff96330',
				'label' => 'Use Parallax Feature',
				'name' => 'use_parallax_feature',
				'type' => 'checkbox',
				'instructions' => 'Should the parallax be displayed?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_5ace9ccb9632f',
				'label' => 'Parallax Content',
				'name' => 'parallax',
				'type' => 'wysiwyg',
				'instructions' => 'Insert parallax content below.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ace9cff96330',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_5a9b0bc39eb99',
				'label' => 'Website Footer',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58f6e76875b84',
				'label' => 'Footer Type',
				'name' => 'footer_type',
				'type' => 'radio',
				'instructions' => 'Select a footer type to feature.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'standard' => 'Standard',
					'simple' => 'Simple',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5ba999318a3dd',
				'label' => 'Copyright Bar Style',
				'name' => 'copyright_bar_style',
				'type' => 'radio',
				'instructions' => 'Should the copyright bar span the full width of the page or be contained?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'fullwidth' => 'Full Width',
					'containerwidth' => 'Container Width',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ad3bb9e899ab',
				'label' => 'Mobile Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ad3bbb0899ac',
				'label' => 'Mobile Header Bar',
				'name' => 'mobile_header_bar',
				'type' => 'radio',
				'instructions' => 'Do you want to include a simple or advanced mobile navigation design?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'simple' => 'Simple',
					'advanced' => 'Advanced',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5a9b0bd59eb9a',
				'label' => 'Miscellaneous',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58ec10c2e7e34',
				'label' => 'Display Search',
				'name' => 'display_search',
				'type' => 'checkbox',
				'instructions' => 'Select to display the search button in the lower right hand portion of the screen.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
					0 => 'display',
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5ac52b7175517',
				'label' => 'Search Location',
				'name' => 'search_location',
				'type' => 'radio',
				'instructions' => 'Select the location of the search button.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58ec10c2e7e34',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'topright' => 'Top Right',
					'topleft' => 'Top Left',
					'bottomright' => 'Bottom Right',
					'bottomleft' => 'Bottom Left',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5ba92b25b4b35',
				'label' => 'Utilize Login Bar',
				'name' => 'utilize_login_bar',
				'type' => 'radio',
				'instructions' => 'Should the website include a user login bar at the top of the page?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ba92b55b4b36',
				'label' => 'Login Bar Style',
				'name' => 'login_bar_style',
				'type' => 'radio',
				'instructions' => 'Should the login bar span the full width of the page or be contained?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ba92b25b4b35',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'fullwidth' => 'Full Width',
					'containerwidth' => 'Container Width',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'fullwidth',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_58e7ecf9d91aa',
		'title' => 'Page Settings',
		'fields' => array(
			array(
				'key' => 'field_5a9b0b2c6347d',
				'label' => 'Page Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58f7a66959e17',
				'label' => 'Page Sub heading',
				'name' => 'page_sub_heading',
				'type' => 'text',
				'instructions' => 'Insert a sub heading for the page does not work on the home page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ad13fc4ce987',
				'label' => 'Secondary Navigation',
				'name' => 'secondary_navigation',
				'type' => 'checkbox',
				'instructions' => 'Display secondary navigation? (requires menu applied to secondary navigation)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_58e7fcde1e7aa',
				'label' => 'Default Editor',
				'name' => 'default_editor',
				'type' => 'checkbox',
				'instructions' => 'Select to display the default editor on the page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Display' => 'Display',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
					0 => 'Display',
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_58e9353a38a37',
				'label' => 'Sidebar Selection',
				'name' => 'sidebar_selection',
				'type' => 'radio',
				'instructions' => 'Do you want to feature the primary sidebar on this page?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58e7fcde1e7aa',
							'operator' => '==',
							'value' => 'Display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left' => 'Left',
					'none' => 'None',
					'right' => 'Right',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'right',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5acfe37a16b41',
				'label' => 'Call Out Boxes',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5acfe39316b42',
				'label' => 'Display Call Out Boxes',
				'name' => 'display_call_out_boxes',
				'type' => 'checkbox',
				'instructions' => 'Do you want to display the call out box feature on this page? Call out boxes are setup in the theme settings tab.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'display' => 'Display',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_5ad032b981a58',
				'label' => 'Shuffle Call Out Boxes',
				'name' => 'shuffle_call_out_boxes',
				'type' => 'checkbox',
				'instructions' => 'Would you like to shuffle call out box items?',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5acfe39316b42',
							'operator' => '==',
							'value' => 'display',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5a9b0b426347e',
				'label' => 'Parallax Feature',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58e93330e3984',
				'label' => 'Use Parallax Feature',
				'name' => 'parallax_feature',
				'type' => 'radio',
				'instructions' => 'Select a parallax feature below.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'Default',
					'custom' => 'Custom',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'none',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array(
				'key' => 'field_58e972f9ded70',
				'label' => 'Parallax Content',
				'name' => 'parallax_content',
				'type' => 'wysiwyg',
				'instructions' => 'If parallax feature is active, insert content here.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58e93330e3984',
							'operator' => '==',
							'value' => 'custom',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_5a9b0b586347f',
				'label' => 'Attention Box Bottom',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58e7ed16bb383',
				'label' => 'Display Attention Box Bottom?',
				'name' => 'attention_bottom',
				'type' => 'checkbox',
				'instructions' => 'Select to display the attention feature on the page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Display' => 'Display',
				),
				'allow_custom' => 0,
				'default_value' => array(
					0 => 'Display',
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_58f81176935bf',
		'title' => 'Page Features',
		'fields' => array(
			array(
				'key' => 'field_5a9b0aca67c8c',
				'label' => 'Gallery',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5915295872546',
				'label' => 'Gallery',
				'name' => 'gallery',
				'type' => 'checkbox',
				'instructions' => 'Use gallery feature?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'use' => 'Use',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_5915299b72547',
				'label' => 'Gallery Content',
				'name' => 'gallery_content',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5915295872546',
							'operator' => '==',
							'value' => 'use',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Gallery Item',
				'sub_fields' => array(
					array(
						'key' => 'field_591529bc72549',
						'label' => 'Gallery Image',
						'name' => 'gallery_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
			array(
				'key' => 'field_5a9b0ada67c8d',
				'label' => 'Accordion',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58f8146d961af',
				'label' => 'Accordion',
				'name' => 'accordion',
				'type' => 'checkbox',
				'instructions' => 'Use accordion feature?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'use' => 'Use',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_58f8117bcce06',
				'label' => 'Accordion Content',
				'name' => 'accordion_content',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58f8146d961af',
							'operator' => '==',
							'value' => 'use',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Section',
				'sub_fields' => array(
					array(
						'key' => 'field_58f814c0961b0',
						'label' => 'Section Heading',
						'name' => 'section_heading',
						'type' => 'text',
						'instructions' => 'Inset a section heading.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_58f814ed961b1',
						'label' => 'Section Content',
						'name' => 'section_content',
						'type' => 'wysiwyg',
						'instructions' => 'Insert the content for the accoridan section.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
				),
			),
			array(
				'key' => 'field_5a9b0af067c8e',
				'label' => 'Tabs',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_58f811b54f473',
				'label' => 'Tabs',
				'name' => 'tabs',
				'type' => 'checkbox',
				'instructions' => 'Use tabs feature?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'use' => 'Use',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
			),
			array(
				'key' => 'field_58f815471d7bb',
				'label' => 'Tabs Content',
				'name' => 'tabs_content',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_58f811b54f473',
							'operator' => '==',
							'value' => 'use',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Section',
				'sub_fields' => array(
					array(
						'key' => 'field_58f815b41d7be',
						'label' => 'Section Number',
						'name' => 'section_number',
						'type' => 'number',
						'instructions' => 'Number the sections 1-6 in order.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => 1,
						'max' => 5,
						'step' => 1,
					),
					array(
						'key' => 'field_58f815671d7bc',
						'label' => 'Section Heading',
						'name' => 'section_heading',
						'type' => 'text',
						'instructions' => 'Insert a section heading.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_58f815a21d7bd',
						'label' => 'Section Content',
						'name' => 'section_content',
						'type' => 'wysiwyg',
						'instructions' => 'Insert section content.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 2,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	endif;
	
?>